steps:
    - name: 'gcr.io/cloud-builders/docker'
      dir:  .
      args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/fairseq-base:latest', '.' ]
images:
    - 'gcr.io/${PROJECT_ID}/fairseq-base:latest'


